apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla-prod-config
data:
  APP_DOMAIN: http://localhost:8888
  DATABASE_NAME: lucky_db
  DATABASE_URL: postgres://lucky:password@vanilla_db_prod:5432/lucky_prod
  HOST: "0.0.0.0"
  HOST_URL: vanillasplit.com
  LUCKY_ENV: production
  PORT: 9000
  POSTGRES_DB: lucky_db
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: 5432
  POSTGRES_USER: lucky
