apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla-prod-config
data:
  HOST: 0.0.0.0
  HOST_URL: 0.0.0.0:9000
  LUCKY_ENV: production
  POD: vanilla-prod
  PORT: 9000
  SEND_GRID_KEY: unused
  BEHIND_PROXY: true
