FROM crystallang/crystal:1.19 AS api-build

# Build all the binaries first
WORKDIR /app

COPY . .

# Install lucky cli
WORKDIR /lucky/cli
ENV LUCKY_ENV=production
RUN git clone https://github.com/luckyframework/lucky_cli . && \
    git checkout v1.4.1 && \
    shards build --without-development && \
    cp bin/lucky /usr/bin

WORKDIR /app
RUN ls
RUN shards install

RUN crystal spec && \
    crystal build --release src/start_server.cr && \
    crystal build --release tasks.cr -o bin/cli && \
    SECRET_KEY_BASE=$(openssl rand -base64 32) shards build vanilla_app

# Now move these binaries over to a thinner image, and ensure it has the postgres-client
FROM alpine:latest

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY --from=api-build bin .

RUN chmod ug+x ./bin/start_server
