FROM crystallang/crystal:latest as lucky-build

# Install lucky cli
WORKDIR /lucky/cli
RUN git clone https://github.com/luckyframework/lucky_cli . && \
    git checkout v1.5.0 && \
    apt update && \
    shards build --without-development

COPY containers/prod/api/entrypoint.sh .

RUN chmod +x entrypoint.sh

# Now build the app
COPY . /app

WORKDIR /app

RUN shards install

# Copy things over to a slimer distro
FROM alpine:latest

RUN apk add --no-cache postgresql-client

# copy over the lucky stuff
COPY --from=lucky-build --chown=root:root /lucky/cli/bin/lucky /usr/bin/.
COPY --from=lucky-build --chown=root:root /bin/shards /usr/bin/.

COPY --from=lucky-build --chown=root:root /app /app

WORKDIR /app
