name: vanilla_app CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  check-format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.19.0
        experimental:
          - false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Format
        run: crystal tool format --check

  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.16.3
        experimental:
          - false
    runs-on: ubuntu-latest
    env:
      LUCKY_ENV: test
      DB_HOST: localhost
    continue-on-error: ${{ matrix.experimental }}

    # TODO - Add proper specs that require our DB
    #
    # services:
    # postgres:
    #   image: postgres:14-alpine
    #   env:
    #     POSTGRES_PASSWORD: postgres
    #   ports:
    #     - 5432:5432
    #   # Set health checks to wait until postgres has started
    #   options: >-
    #     --health-cmd pg_isready
    #     --health-interval 10s
    #     --health-timeout 5s
    #     --health-retries 5
    steps:
      # Backend
      - uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}

      - name: Set up Crystal cache
        uses: actions/cache@v4
        id: crystal-cache
        with:
          path: |
            ~/.cache/crystal
            lib
          key: ${{ runner.os }}-crystal-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-

      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards check || shards install

      - name: Build lucky_tasks
        run: crystal build tasks.cr -o ./lucky_tasks

      # - name: Prepare database
      #   run: |
      #     ./lucky_tasks db.create
      #     ./lucky_tasks db.migrate
      #     ./lucky_tasks db.seed.required_data

      - name: Run tests
        run: crystal spec

      # Frontend
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install JS dependencies
        working-directory: src/ts
        run: bun install

      - name: Compile assets
        working-directory: src/ts
        run: bun prod

  build-and-push:
    needs: [check-format, specs]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into the GH Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build \
            -f containers/prod/api/Containerfile \
            -t ghcr.io/${{ github.repository }}/vanilla_prod_api:latest \
            -t ghcr.io/${{ github.repository }}/vanilla_prod_api:${{ github.sha }} \
            .

      - name: Build scheduler image
        run: |
          docker build \
            -f containers/prod/scheduler/Containerfile \
            -t ghcr.io/${{ github.repository }}/vanilla_prod_scheduler:latest \
            -t ghcr.io/${{ github.repository }}/vanilla_prod_scheduler:${{ github.sha }} \
            containers/prod/scheduler

      - name: Push the images
        run: |
            docker push ghcr.io/${{ github.repository }}/vanilla_prod_api:latest
            docker push ghcr.io/${{ github.repository }}/vanilla_prod_scheduler:latest
